# AWS Provider Credentials Template
# Create Secret for AWS credentials used by CAPA (Cluster API Provider AWS)
# IMPORTANT: Replace placeholder values before applying
---
apiVersion: v1
kind: Secret
metadata:
  name: capa-manager-bootstrap-credentials
  namespace: capa-system # Default namespace for AWS provider
type: Opaque
stringData:
  # AWS programmatic access credentials
  # Create an IAM user with appropriate permissions (see below)
  credentials: |
    [default]
    aws_access_key_id = <YOUR_ACCESS_KEY_ID>
    aws_secret_access_key = <YOUR_SECRET_ACCESS_KEY>
    # Optional: for session tokens (temporary credentials)
    # aws_session_token = <YOUR_SESSION_TOKEN>
    region = us-east-1

---
# Alternative: Using eksctl to create the required IAM resources
# This creates the policies and roles needed by CAPA
#
# eksctl utils associate-iam-oidc-provider --cluster <management-cluster> --approve
#
# eksctl create iamserviceaccount \
#   --name capa-controller-manager \
#   --namespace capa-system \
#   --cluster <management-cluster> \
#   --attach-policy-arn arn:aws:iam::aws:policy/AmazonEC2FullAccess \
#   --attach-policy-arn arn:aws:iam::aws:policy/IAMFullAccess \
#   --attach-policy-arn arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess \
#   --approve

---
# IAM Policy for CAPA controller (minimum permissions)
# Create this policy and attach to the IAM user/role
#
# {
#   "Version": "2012-10-17",
#   "Statement": [
#     {
#       "Effect": "Allow",
#       "Action": [
#         "ec2:*",
#         "elasticloadbalancing:*",
#         "autoscaling:*",
#         "iam:CreateServiceLinkedRole",
#         "iam:PassRole",
#         "iam:GetInstanceProfile",
#         "iam:CreateInstanceProfile",
#         "iam:DeleteInstanceProfile",
#         "iam:AddRoleToInstanceProfile",
#         "iam:RemoveRoleFromInstanceProfile",
#         "ssm:GetParameter"
#       ],
#       "Resource": "*"
#     },
#     {
#       "Effect": "Allow",
#       "Action": [
#         "iam:CreateRole",
#         "iam:DeleteRole",
#         "iam:AttachRolePolicy",
#         "iam:DetachRolePolicy",
#         "iam:GetRole",
#         "iam:ListAttachedRolePolicies"
#       ],
#       "Resource": "arn:aws:iam::*:role/control-plane.cluster-api-provider-aws.sigs.k8s.io"
#     },
#     {
#       "Effect": "Allow",
#       "Action": [
#         "iam:CreateRole",
#         "iam:DeleteRole",
#         "iam:AttachRolePolicy",
#         "iam:DetachRolePolicy",
#         "iam:GetRole",
#         "iam:ListAttachedRolePolicies"
#       ],
#       "Resource": "arn:aws:iam::*:role/nodes.cluster-api-provider-aws.sigs.k8s.io"
#     }
#   ]
# }

---
# Environment variables for clusterctl (place in ~/.bashrc or export before init)
#
# export AWS_REGION=us-east-1
# export AWS_ACCESS_KEY_ID=<YOUR_ACCESS_KEY_ID>
# export AWS_SECRET_ACCESS_KEY=<YOUR_SECRET_ACCESS_KEY>
#
# # For EKS-based control plane
# export AWS_SESSION_TOKEN=<YOUR_SESSION_TOKEN>  # if using temporary credentials
#
# # SSH key for node access
# export AWS_SSH_KEY_NAME=<YOUR_SSH_KEY_NAME>
#
# # Control plane settings
# export AWS_CONTROL_PLANE_MACHINE_TYPE=m5.large
# export CONTROL_PLANE_MACHINE_COUNT=3
#
# # Worker settings
# export AWS_NODE_MACHINE_TYPE=m5.xlarge
# export WORKER_MACHINE_COUNT=3

---
# Initialize AWS provider:
#
# export AWS_B64ENCODED_CREDENTIALS=$(clusterctl generate provider aws -f)
# clusterctl init --infrastructure aws

---
# ClusterAWS identity types available:
#
# 1. AWSClusterStaticIdentity - static AWS credentials (this template)
# 2. AWSClusterRoleIdentity - assume IAM role
# 3. AWSClusterControllerIdentity - use controller's credentials
#
# Example AWSClusterRoleIdentity:
#
# apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
# kind: AWSClusterRoleIdentity
# metadata:
#   name: cross-account-role
# spec:
#   allowedNamespaces:
#     list:
#       - default
#   roleARN: arn:aws:iam::ACCOUNT_ID:role/CAPIRole
#   sourceIdentityRef:
#     kind: AWSClusterControllerIdentity
#     name: default
